# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCadastroveiculo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cadastroveiculo(self):
    self.driver.get("http://localhost:8080/RevendaVeiculosSpringMVC/veiculos")
    self.driver.set_window_size(888, 696)
    self.driver.find_element(By.LINK_TEXT, "Novo Veículo").click()
    self.driver.find_element(By.ID, "anoFabricacao").click()
    self.driver.find_element(By.ID, "anoFabricacao").send_keys("2010")
    self.driver.find_element(By.ID, "placa").click()
    self.driver.find_element(By.ID, "placa").send_keys("LJI-5502")
    self.driver.find_element(By.ID, "cilindradas").click()
    self.driver.find_element(By.ID, "cilindradas").send_keys("100")
    self.driver.find_element(By.ID, "chassi").click()
    self.driver.find_element(By.ID, "chassi").send_keys("abc123abc")
    self.driver.find_element(By.NAME, "arquivoFoto").click()
    self.driver.find_element(By.NAME, "arquivoFoto").send_keys("C:\\fakepath\\44g7bqjk4jq71.png")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.close()
  
