# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchveiculo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchveiculo(self):
    self.driver.get("http://localhost:8080/RevendaVeiculosSpringMVC/veiculos")
    self.driver.set_window_size(888, 696)
    self.driver.find_element(By.ID, "selectCampo").click()
    self.driver.find_element(By.ID, "inputValor").click()
    self.driver.find_element(By.ID, "inputValor").send_keys("2010")
    self.driver.find_element(By.ID, "select2-selectModelo-container").click()
    self.driver.find_element(By.ID, "btnBuscar").click()
  
