# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBuyveichle():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_buyveichle(self):
    self.driver.get("http://localhost:8080/RevendaVeiculosSpringMVC/veiculos")
    self.driver.set_window_size(888, 696)
    self.driver.find_element(By.LINK_TEXT, "TRANSAÇÕES").click()
    self.driver.find_element(By.LINK_TEXT, "Iniciar compra").click()
    self.driver.find_element(By.ID, "placa").click()
    self.driver.find_element(By.ID, "placa").send_keys("MNT1020")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "txtData").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .day:nth-child(6)").click()
    self.driver.find_element(By.ID, "txtPreco").click()
    self.driver.find_element(By.ID, "txtPreco").send_keys("6000")
    self.driver.find_element(By.ID, "txtObs").click()
    self.driver.find_element(By.ID, "txtObs").send_keys("veiculo bom para compra")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close > span").click()
  
